# Generated by Django 5.1.3 on 2024-11-08 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('candidate_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('manifesto', models.TextField()),
                ('department', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=50)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='candidate_photos/')),
                ('vote_count', models.IntegerField(default=0)),
            ],
        ),
    ]
