# Generated by Django 5.1.3 on 2025-02-08 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0007_election_results'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='password',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
