# Generated by Django 5.1.3 on 2025-02-08 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0008_candidate_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='password',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
