# Generated by Django 5.1.3 on 2025-02-13 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0010_candidate_registration_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='registration_number',
        ),
        migrations.AlterField(
            model_name='candidate',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
