# Generated by Django 5.1.3 on 2025-02-28 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0012_election_results_calculated'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
